global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'resume-app'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['app-blue:3000', 'app-green:3000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
